### ISSUE TITLE
create scripts to complement setup.md

### ISSUE THREAD

**Issue by ralphtheninja** [MrChrisJ/fullnode#15]
Having instructions is good, but scripts are better. So instead of having to manually copy pasting lines from the markdown file, you just run a single script that performs everything needed to get the software in order.

We could also provide default configuration files in this repository that basically only need to be copied to the device (by the script of course).

I could start writing something if you like and we can gradually pull in things as we need them.

**Comment by ralphtheninja** [comment]
I might have some scripts in my dotfiles that we can use as a base, e.g. the script for installing bitcoin looks similar to yours (in fact I think I got them from there from the beginning). See https://github.com/ralphtheninja/dotfiles/blob/master/install-bitcoin

**Comment by ralphtheninja** [comment]
We could also add simple tools/scripts, add them to `$PATH` (via `.bashrc`) when installing the fullnode.

**Comment by MrChrisJ** [comment]
Hey @ralphtheninja that's fantastic thanks. It would be great to make it a bit more interactive. For example giving people a choice of which branch of the code to install and what parameters they want in the bitcoin.conf file.   

Also what would be good is their ability to choose which fork eg Bitcoin Classic. I am aware this will be controversial but having given it some thought I do not think it is up to me to tell people which fork to use. Bitcoin's open source licence was one of its key defining characteristics. If Core are right then they need to succeed on their own merits even in the presence of a network fork that has big money behind it.

**Comment by ralphtheninja** [comment]
> Hey @ralphtheninja that's fantastic thanks. It would be great to make it a bit more interactive. For example giving people a choice of which branch of the code to install and what parameters they want in the bitcoin.conf file.

I agree. But lets not implement all features at once ;) We can start with scripts and then tune them once we have something up.
