### ISSUE TITLE
Data not going to USB but on sd card

### ISSUE THREAD

**Issue by nolegalname** [MrChrisJ/fullnode#7]
Hi,

Have problem with USB think and need some assistance.

First was think that there is no enough power for all USB ports (was use NOKIA phone battery charger)than get new adapter and node start OK  after new installation of conf.but than after some time get message that there is not enough disc spacejust 50MB of 7.7Gbof sd card

Was check all and delite all files blocks,  datseabase and chainstatefrom home/pi/.bitcoin. Than start checking again all see pictures:
![img_3266 1](https://cloud.githubusercontent.com/assets/16581374/12531408/0fe61718-c1fa-11e5-88e5-e373590e41e9.JPG)
![img_3267 1](https://cloud.githubusercontent.com/assets/16581374/12531412/1ee89b3c-c1fa-11e5-9abf-ebc26f9249ee.JPG)

Again start node:
![img_3271 1](https://cloud.githubusercontent.com/assets/16581374/12531419/55de1856-c1fa-11e5-9928-e92c6f56f030.JPG)
Than was check again home/pi/.bitcoin folder and inside is again blocks,  datseabase and chainstate
![img_3274 1](https://cloud.githubusercontent.com/assets/16581374/12531424/72d92d10-c1fa-11e5-9e83-86ac1f65a001.JPG)
![img_3273 1](https://cloud.githubusercontent.com/assets/16581374/12531427/7c092d36-c1fa-11e5-9c2b-12a399b3d03d.JPG)

Need assistance how to solve this problem ASAP

**Comment by nolegalname** [comment]
Here are thepictures first 3.1 Gb free space 
![img_3276 1](https://cloud.githubusercontent.com/assets/16581374/12531523/639b2af8-c1fd-11e5-94d4-662c81b3b26f.JPG)
and node was
![img_3275 1](https://cloud.githubusercontent.com/assets/16581374/12531525/7a1fd4ae-c1fd-11e5-9ec1-db3ff3f1af77.JPG)

And than 3.0 Gb free space
![img_3277 1](https://cloud.githubusercontent.com/assets/16581374/12531529/8e5f9eea-c1fd-11e5-80bd-6ea084d11bb0.JPG)

Node is:
![img_3278 1](https://cloud.githubusercontent.com/assets/16581374/12531534/9a572f4c-c1fd-11e5-8450-389b3c506131.JPG)

**Comment by ghost** [comment]
The blockchain is over 60gb of data ... i think you need to get a biger SD card or put your blockchain data onto a usb stick with at least 128gb

**Comment by nolegalname** [comment]
have USB128 GB, but not know how to put data on USB

**Comment by nolegalname** [comment]
have 8 GB sd card and 128GB USB on raspberry P2

**Comment by nolegalname** [comment]
and is not asking where to put data just downloading to sd card

**Comment by ghost** [comment]
you can edit the bitcoin.conf file or you can specifiy it when you start bitcoind using the -datadir=<dir>  switch

**Comment by nolegalname** [comment]
can u write how to do that?

**Comment by nolegalname** [comment]
where inbitcoin.conffile and what to write using-datadir=switch

**Comment by nolegalname** [comment]
not so skilled with commands

**Comment by ghost** [comment]
sorry just looked and you cant edit the bitcoin.conf .. you must specifiy the dir using the command line switch when starting bitcoind .. so if you start bitcoind by typing command "bitcoind &" then you should start by typing "bitcoind -datadir=/xxx/yyy/zzz &" where xxx/yyy/zzz is the path you want to use ... without knowing the path you want to use i cant supply exact command

**Comment by nolegalname** [comment]
think this is USB     /dev/sda1

**Comment by nolegalname** [comment]
where to check and how to check this /xxx/yyy/zzz

**Comment by ghost** [comment]
ok so if you make a folder on the usb called bitcoin and then put 

/dev/sda1/bitcoin 

does that get the data downloading to the usb ? .. you will see the amount of free space dropping if it does

**Comment by nolegalname** [comment]
here is pic of media
![img_3280 1](https://cloud.githubusercontent.com/assets/16581374/12531691/76710c84-c201-11e5-8d77-be3bdc372221.JPG)

**Comment by ghost** [comment]
ok try 
bitcoind -datadir=/media/bitcoindata &
as the command to start the node

**Comment by nolegalname** [comment]
done that and this is what get:

![img_3282 1](https://cloud.githubusercontent.com/assets/16581374/12531743/e3a35afe-c202-11e5-8536-fb05925ed6b6.JPG)

**Comment by nolegalname** [comment]
and this 
![img_3283 1](https://cloud.githubusercontent.com/assets/16581374/12531775/a6149a3a-c203-11e5-85c5-ed715d1d76d2.JPG)

**Comment by ghost** [comment]
where you have done
bitcoind -datadir=/media/bitcoindata & bitcoind -daemon 
is not right as your launching bitcoin twice with different options - and as you can see from the final status message in the 1st screen above bitcoind is already running in the back ground - make sure your bitcoind is stopped using "bitcoin-cli stop" to stop it - then try starting it again but only use 
bitcoind -datadir=/media/bitcoindata & 
and again in second screen shot - is not correct eg.
bitcoind -datadir=/dev/sda1/ /media/bitcoindata  
you can not have spaces in the path switch

**Comment by ghost** [comment]
what does the file manager in the gui show as the path to the folder on the usb where you want to download to ?

**Comment by nolegalname** [comment]
will try

![img_3287 1](https://cloud.githubusercontent.com/assets/16581374/12531810/697d1524-c204-11e5-8e3a-ec3aa127c1d4.JPG)
check this pic

**Comment by nolegalname** [comment]
get message about error when type to stop bitcoin-cli
![img_3288 1](https://cloud.githubusercontent.com/assets/16581374/12531822/e19afd46-c204-11e5-95bc-63e8337eafd2.JPG)

file manager showing:

![img_3290 1](https://cloud.githubusercontent.com/assets/16581374/12531825/ff1c1a6c-c204-11e5-845d-f261537bd53e.JPG)
![img_3291 1](https://cloud.githubusercontent.com/assets/16581374/12531828/094fa6b6-c205-11e5-9733-56d15950b8fc.JPG)

**Comment by ghost** [comment]
i dont see the usb stick in the filemanage gui - just your home (sd card) stuff

**Comment by nolegalname** [comment]
![img_3292 1](https://cloud.githubusercontent.com/assets/16581374/12531875/358365a0-c206-11e5-9617-60e1fe0069cf.JPG)

**Comment by nolegalname** [comment]
me was think that second is USB

**Comment by nolegalname** [comment]
what is than last folder on second picture of file manager

**Comment by ghost** [comment]
is that not the root of the sd card?  I would expect the usb to be am empty drive apart from one folder you may have made called bitcoin or bitcoindata or something like that - not all those files that are visiblein that screen shot

**Comment by nolegalname** [comment]
but USB came with data on it together with sd card

**Comment by ghost** [comment]
try

bitcoind -datadir=/media &

**Comment by nolegalname** [comment]
get this
![img_3295 1](https://cloud.githubusercontent.com/assets/16581374/12531953/bcce1040-c207-11e5-9dec-331e8e3b380e.JPG)

**Comment by ghost** [comment]
also try 

bitcoind -datadir=/bitcoindata &

**Comment by nolegalname** [comment]
not know why is not working command stop

**Comment by ghost** [comment]
yes you must stop bitcoin-cli before you can restart it with new options .. and it seems you need to wait for it to stop activating best chain and start downloading blocks again before it will stop

**Comment by nolegalname** [comment]
me put this command to stop client few times in past 20 30 min and not know why is activated

**Comment by nolegalname** [comment]
same message to stop ant to check client
![img_3298 1](https://cloud.githubusercontent.com/assets/16581374/12531984/72dae6ba-c208-11e5-89f9-7c82382c7524.JPG)

**Comment by nolegalname** [comment]
maybe is running who knows

**Comment by nolegalname** [comment]
same amount of data in file manager

**Comment by ghost** [comment]
it seems to have crashed?  .. due to it having same amount of data in folder - eg its not getting more as its never getting past 'activating best chain' which should never take more than a few mins

**Comment by ghost** [comment]
check the readme for this project

"You may spend a long time on the “Activating Best Chain” progress report, this is a known issue in bitcoin and will be fixed in version 0.12. Once it loads you will be in the GUI where you can go to the menu and click Help>Debug Window to get nice graphs on network usage."

so perhaps best to wait until its loaded - then stop it then restart with -datadir option

**Comment by nolegalname** [comment]
thnx
will do that

**Comment by ghost** [comment]
from looking at the screen shots above it seems bitcoinData is /dev/sda1 the usb stick .. so try  
bitcoind -datadir=/home/pi/bitcoinData &

**Comment by MrChrisJ** [comment]
Hi,

To get Bitcoind to load the blockchain data you need to mount the external USB on startup to the home/pi/.bitcoin directory. Before you do stop bitcoin from running with the command:

```
bitcoin-cli stop
```

Then delete the files in /.bitcoin directory as they will just take up space.

If the USB stick doesn't mount to /.bitcoin on startup and Bitcoind starts running it will create new files in the home/pi/.bitcoin directory stored on the SD Card which will run out of space very quickly. Therefore you need to do the following before going forward:

```
sudo blkid
```

Now note down the UUID number of the /dev/sda disk. Next do:

```
sudo nano /etc/fstab/
```

That will open up a directory and you will probably have a line already that reads something like:

```
UUID=B836-1605    /home/pi/.bitcoin    vfat uid=pi,gid=pi,umask=0022,sync,auto,nosuid,rw,nouser    0    0
```

You need to change the UUID to match that of the /dev/sda that you noted down before. Now cntr+X and hit "y" and Enter to exit while saving changes. Now if you reboot it should mount the root folder of the USB Drive to the home/pi/.bitcoin directory and when bitcoind loads and it should load up the bitcoin data from that folder.

The reason this might fail is because the Pi isn't getting enough power and it will shut down peripherals or may crash if you have too much plugged in. You need a good 2000 mA power supply with good quality micro USB cable. You will know if it is under powered because a square rainbow symbol will appear in the top right corner of the screen. If you are getting this it means either the power isn't enough or you have too much plugged in the pi.  

To rule this out you can make sure the USB drive works reliably on a windows machine. It is formatted in FAT32 and will work as is. You can even run Bitcoin QT on your desktop as a test and sync the blockchain on it. If it works find on another computer that points towards the Pi being the problem.

Let us know how you get on or if you need any clarification.

**Comment by nolegalname** [comment]
hi
 typed command sudo nano /etc/fstab/
and open a directory and no lines there, me paste line with UUID but not working-something is missing some line or not know what
![img_3310 1](https://cloud.githubusercontent.com/assets/16581374/12535197/d38ecd32-c27b-11e5-8fca-3c12095954ca.JPG)

**Comment by nolegalname** [comment]
is it possible to download this nodefrom netand start from begining

**Comment by nolegalname** [comment]
here are information about Pi
pi@fullnode ~ $ dmesg
[    0.000000] Booting Linux on physical CPU 0xf00
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 4.1.13-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015
[    0.000000] CPU: ARMv7 Processor [410fc075] revision 5 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: Raspberry Pi 2 Model B Rev 1.1
[    0.000000] cma: Reserved 8 MiB at 0x3a800000
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] On node 0 totalpages: 241664
[    0.000000] free_area_init_node: node 0, pgdat 8085f000, node_mem_map b9fa6000
[    0.000000]   Normal zone: 2124 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 241664 pages, LIFO batch:31
[    0.000000] [bcm2709_smp_init_cpus] enter (9420->f3003010)
[    0.000000] [bcm2709_smp_init_cpus] ncores=4
[    0.000000] PERCPU: Embedded 13 pages/cpu @b9f64000 s20608 r8192 d24448 u53248
[    0.000000] pcpu-alloc: s20608 r8192 d24448 u53248 alloc=13*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 239540
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1824 bcm2708_fb.fbheight=984 bcm2709.boardrev=0xa01041 bcm2709.serial=0x3a9fff5d smsc95xx.macaddr=B8:27:EB:9F:FF:5D bcm2708_fb.fbswap=1 bcm2709.disk_led_gpio=47 bcm2709.disk_led_active_low=0 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x3dc00000 vc_mem.mem_size=0x3f000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait
[    0.000000] PID hash table entries: 4096 (order: 2, 16384 bytes)
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 939496K/966656K available (5967K kernel code, 534K rwdata, 1652K rodata, 420K init, 757K bss, 18968K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xbb800000 - 0xff000000   (1080 MB)
[    0.000000]     lowmem  : 0x80000000 - 0xbb000000   ( 944 MB)
[    0.000000]     modules : 0x7f000000 - 0x80000000   (  16 MB)
[    0.000000]       .text : 0x80008000 - 0x80778f64   (7620 kB)
[    0.000000]       .init : 0x80779000 - 0x807e2000   ( 420 kB)
[    0.000000]       .data : 0x807e2000 - 0x80867b6c   ( 535 kB)
[    0.000000]        .bss : 0x8086a000 - 0x8092779c   ( 758 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] 	Additional per-CPU info printed with stalls.
[    0.000000] NR_IRQS:608
[    0.000000] Architected cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000010] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000031] Switching to timer-based delay loop, resolution 52ns
[    0.000319] Console: colour dummy device 80x30
[    0.002065] console [tty1] enabled
[    0.002128] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.002228] pid_max: default: 32768 minimum: 301
[    0.002611] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.002677] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.003999] Initializing cgroup subsys blkio
[    0.004084] Initializing cgroup subsys memory
[    0.004153] Initializing cgroup subsys devices
[    0.004214] Initializing cgroup subsys freezer
[    0.004290] Initializing cgroup subsys net_cls
[    0.004402] CPU: Testing write buffer coherency: ok
[    0.004524] ftrace: allocating 20235 entries in 60 pages
[    0.053971] CPU0: update cpu_capacity 1024
[    0.054056] CPU0: thread -1, cpu 0, socket 15, mpidr 80000f00
[    0.054104] [bcm2709_smp_prepare_cpus] enter
[    0.054268] Setting up static identity map for 0x8240 - 0x8274
[    0.113824] [bcm2709_boot_secondary] cpu:1 started (0) 18
[    0.114263] [bcm2709_secondary_init] enter cpu:1
[    0.114321] CPU1: update cpu_capacity 1024
[    0.114329] CPU1: thread -1, cpu 1, socket 15, mpidr 80000f01
[    0.133804] [bcm2709_boot_secondary] cpu:2 started (0) 18
[    0.134170] [bcm2709_secondary_init] enter cpu:2
[    0.134202] CPU2: update cpu_capacity 1024
[    0.134210] CPU2: thread -1, cpu 2, socket 15, mpidr 80000f02
[    0.153851] [bcm2709_boot_secondary] cpu:3 started (0) 17
[    0.154107] [bcm2709_secondary_init] enter cpu:3
[    0.154136] CPU3: update cpu_capacity 1024
[    0.154144] CPU3: thread -1, cpu 3, socket 15, mpidr 80000f03
[    0.154238] Brought up 4 CPUs
[    0.154372] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.154414] CPU: All CPU(s) started in HYP mode.
[    0.154449] CPU: Virtualization extensions available.
[    0.155483] devtmpfs: initialized
[    0.179796] VFP support v0.3: implementor 41 architecture 2 part 30 variant 7 rev 5
[    0.180185] clocksource jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.181336] pinctrl core: initialized pinctrl subsystem
[    0.182179] NET: Registered protocol family 16
[    0.187953] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[    0.189180] bcm2709.uart_clock = 3000000
[    0.194480] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.194551] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.194774] Serial: AMBA PL011 UART driver
[    0.194988] 3f201000.uart: ttyAMA0 at MMIO 0x3f201000 (irq = 83, base_baud = 0) is a PL011 rev2
[    0.700221] console [ttyAMA0] enabled
[    0.704481] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.786341] bcm2708-dmaengine 3f007000.dma: DMA legacy API manager at f3007000, dmachans=0xf35
[    0.795102] bcm2708-dmaengine 3f007000.dma: Initialized 7 DMA channels (+ 1 legacy)
[    0.803515] bcm2708-dmaengine 3f007000.dma: Load BCM2835 DMA engine driver
[    0.810442] bcm2708-dmaengine 3f007000.dma: dma_debug:0
[    0.816415] SCSI subsystem initialized
[    0.820458] usbcore: registered new interface driver usbfs
[    0.826071] usbcore: registered new interface driver hub
[    0.831558] usbcore: registered new device driver usb
[    0.837325] raspberrypi-firmware soc:firmware: Attached to firmware from 2015-11-18 15:43
[    0.872874] Switched to clocksource arch_sys_counter
[    0.927062] FS-Cache: Loaded
[    0.930351] CacheFiles: Loaded
[    0.945151] NET: Registered protocol family 2
[    0.950833] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.958100] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.964814] TCP: Hash tables configured (established 8192 bind 8192)
[    0.971304] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.977332] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.984094] NET: Registered protocol family 1
[    0.988911] RPC: Registered named UNIX socket transport module.
[    0.994930] RPC: Registered udp transport module.
[    0.999659] RPC: Registered tcp transport module.
[    1.004416] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.012090] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 5 counters available
[    1.021720] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    1.043748] VFS: Disk quotas dquot_6.6.0
[    1.048084] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    1.057684] FS-Cache: Netfs 'nfs' registered for caching
[    1.064244] NFS: Registering the id_resolver key type
[    1.069378] Key type id_resolver registered
[    1.073623] Key type id_legacy registered
[    1.080450] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    1.088133] io scheduler noop registered
[    1.092090] io scheduler deadline registered (default)
[    1.097599] io scheduler cfq registered
[    1.104099] BCM2708FB: allocated DMA memory fac00000
[    1.109125] BCM2708FB: allocated DMA channel 0 @ f3007000
[    1.144015] Console: switching to colour frame buffer device 228x61
[    1.168501] Serial: 8250/16550 driver, 0 ports, IRQ sharing disabled
[    1.176335] vc-cma: Videocore CMA driver
[    1.180346] vc-cma: vc_cma_base      = 0x00000000
[    1.185168] vc-cma: vc_cma_size      = 0x00000000 (0 MiB)
[    1.190665] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
[    1.196442] vc-mem: phys_addr:0x00000000 mem_base=0x3dc00000 mem_size:0x3f000000(1008 MiB)
[    1.220852] brd: module loaded
[    1.233189] loop: module loaded
[    1.237451] vchiq: vchiq_init_state: slot_zero = 0xbac80000, is_master = 0
[    1.246442] Loading iSCSI transport class v2.0-870.
[    1.252438] usbcore: registered new interface driver smsc95xx
[    1.258446] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.464703] Core Release: 2.80a
[    1.467925] Setting default values for core params
[    1.472842] Finished setting default values for core params
[    1.678954] Using Buffer DMA mode
[    1.682342] Periodic Transfer Interrupt Enhancement - disabled
[    1.688302] Multiprocessor Interrupt Enhancement - disabled
[    1.694002] OTG VER PARAM: 0, OTG VER FLAG: 0
[    1.698447] Dedicated Tx FIFOs mode
[    1.702377] WARN::dwc_otg_hcd_init:1047: FIQ DMA bounce buffers: virt = 0xbac14000 dma = 0xfac14000 len=9024
[    1.712443] FIQ FSM acceleration enabled for :
[    1.712443] Non-periodic Split Transactions
[    1.712443] Periodic Split Transactions
[    1.712443] High-Speed Isochronous Endpoints
[    1.729494] dwc_otg: Microframe scheduler enabled
[    1.729573] WARN::hcd_init_fiq:412: FIQ on core 1 at 0x80402c54
[    1.740334] WARN::hcd_init_fiq:413: FIQ ASM at 0x80402fb0 length 36
[    1.751402] WARN::hcd_init_fiq:438: MPHI regs_base at 0xbb89a000
[    1.762250] dwc_otg 3f980000.usb: DWC OTG Controller
[    1.772057] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    1.784226] dwc_otg 3f980000.usb: irq 32, io mem 0x00000000
[    1.794624] Init: Port Power? op_state=1
[    1.803290] Init: Power Port (0)
[    1.811496] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.823057] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.835048] usb usb1: Product: DWC OTG Controller
[    1.844507] usb usb1: Manufacturer: Linux 4.1.13-v7+ dwc_otg_hcd
[    1.855340] usb usb1: SerialNumber: 3f980000.usb
[    1.865688] hub 1-0:1.0: USB hub found
[    1.874339] hub 1-0:1.0: 1 port detected
[    1.883499] dwc_otg: FIQ enabled
[    1.883512] dwc_otg: NAK holdoff enabled
[    1.883523] dwc_otg: FIQ split-transaction FSM enabled
[    1.883563] Module dwc_common_port init
[    1.883979] usbcore: registered new interface driver usb-storage
[    1.895019] mousedev: PS/2 mouse device common for all mice
[    1.906201] bcm2835-cpufreq: min=600000 max=700000
[    1.916065] sdhci: Secure Digital Host Controller Interface driver
[    1.926966] sdhci: Copyright(c) Pierre Ossman
[    1.936454] mmc-bcm2835 3f300000.mmc: mmc_debug:0 mmc_debug2:0
[    1.946976] mmc-bcm2835 3f300000.mmc: DMA channels allocated
[    1.993253] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.007648] ledtrig-cpu: registered to indicate activity on CPUs
[    2.018614] hidraw: raw HID events driver (C) Jiri Kosina
[    2.030003] usbcore: registered new interface driver usbhid
[    2.041336] usbhid: USB HID core driver
[    2.052349] Initializing XFRM netlink socket
[    2.061413] NET: Registered protocol family 17
[    2.073009] Key type dns_resolver registered
[    2.082365] Registering SWP/SWPB emulation handler
[    2.083034] Indeed it is in host mode hprt0 = 00021501
[    2.100834] mmc0: host does not support reading read-only switch, assuming write-enable
[    2.103101] mmc0: new high speed SDHC card at address 0001
[    2.103746] mmcblk0: mmc0:0001 SD8GB 7.32 GiB 
[    2.105989]  mmcblk0: p1 p2
[    2.142235] registered taskstats version 1
[    2.151305] vc-sm: Videocore shared memory driver
[    2.160728] [vc_sm_connected_init]: start
[    2.170192] [vc_sm_connected_init]: end - returning 0
[    2.197896] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.210933] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    2.224252] devtmpfs: mounted
[    2.232667] Freeing unused kernel memory: 420K (80779000 - 807e2000)
[    2.262959] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.274612] Indeed it is in host mode hprt0 = 00001101
[    2.483347] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.495381] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.508501] hub 1-1:1.0: USB hub found
[    2.518160] hub 1-1:1.0: 5 ports detected
[    2.802981] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.913584] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    2.925475] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.942286] smsc95xx v1.0.4
[    3.008249] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:9f:ff:5d
[    3.102977] usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[    3.214720] usb 1-1.2: New USB device found, idVendor=0bda, idProduct=8178
[    3.227415] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.240621] usb 1-1.2: Product: USB WLAN
[    3.250765] usb 1-1.2: Manufacturer: 802.11n
[    3.260813] usb 1-1.2: SerialNumber: 00e04c000001
[    3.352981] usb 1-1.3: new high-speed USB device number 5 using dwc_otg
[    3.463917] usb 1-1.3: New USB device found, idVendor=0781, idProduct=5567
[    3.476333] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.489307] usb 1-1.3: Product: Cruzer Blade
[    3.499167] usb 1-1.3: Manufacturer: SanDisk
[    3.508968] usb 1-1.3: SerialNumber: 4C530201840308101442
[    3.521075] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[    3.534075] scsi host0: usb-storage 1-1.3:1.0
[    3.558047] udevd[177]: starting version 175
[    3.622998] usb 1-1.4: new low-speed USB device number 6 using dwc_otg
[    3.767986] usb 1-1.4: New USB device found, idVendor=04f3, idProduct=0103
[    3.780961] usb 1-1.4: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.807894] input: HID 04f3:0103 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/0003:04F3:0103.0001/input/input0
[    3.883469] hid-generic 0003:04F3:0103.0001: input,hidraw0: USB HID v1.11 Keyboard [HID 04f3:0103] on usb-3f980000.usb-1.4/input0
[    3.916397] input: HID 04f3:0103 as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.1/0003:04F3:0103.0002/input/input1
[    3.993491] hid-generic 0003:04F3:0103.0002: input,hidraw1: USB HID v1.11 Device [HID 04f3:0103] on usb-3f980000.usb-1.4/input1
[    4.093038] usb 1-1.5: new low-speed USB device number 7 using dwc_otg
[    4.232062] usb 1-1.5: New USB device found, idVendor=046d, idProduct=c03e
[    4.250071] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    4.269495] usb 1-1.5: Product: USB-PS/2 Optical Mouse
[    4.285031] usb 1-1.5: Manufacturer: Logitech
[    4.314759] input: Logitech USB-PS/2 Optical Mouse as /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.5/1-1.5:1.0/0003:046D:C03E.0003/input/input2
[    4.343343] hid-generic 0003:046D:C03E.0003: input,hidraw2: USB HID v1.10 Mouse [Logitech USB-PS/2 Optical Mouse] on usb-3f980000.usb-1.5/input0
[    4.423311] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    4.544927] scsi 0:0:0:0: Direct-Access     SanDisk  Cruzer Blade     1.27 PQ: 0 ANSI: 6
[    4.567054] sd 0:0:0:0: [sda] 250085376 512-byte logical blocks: (128 GB/119 GiB)
[    4.585116] sd 0:0:0:0: [sda] Write Protect is off
[    4.598135] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[    4.599160] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[    4.634856]  sda: sda1
[    4.652664] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    4.669954] sd 0:0:0:0: Attached scsi generic sg0 type 0
[    4.797770] random: nonblocking pool is initialized
[    4.924489] usbcore: registered new interface driver rtl8192cu
[    6.620466] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    6.954444] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   12.938132] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   17.212295] cfg80211: Calling CRDA to update world regulatory domain
[   17.677603] Adding 102396k swap on /var/swap.  Priority:-1 extents:2 across:2134012k SSFS
[   20.352951] cfg80211: Calling CRDA to update world regulatory domain
[   23.502992] cfg80211: Calling CRDA to update world regulatory domain
[   26.653082] cfg80211: Calling CRDA to update world regulatory domain
[   26.689350] uart-pl011 3f201000.uart: no DMA platform data
[   29.803086] cfg80211: Calling CRDA to update world regulatory domain
[   32.953107] cfg80211: Calling CRDA to update world regulatory domain
[   36.103124] cfg80211: Calling CRDA to update world regulatory domain
[   39.254298] cfg80211: Calling CRDA to update world regulatory domain
[   42.403092] cfg80211: Calling CRDA to update world regulatory domain
[   45.553154] cfg80211: Calling CRDA to update world regulatory domain
[   48.703096] cfg80211: Calling CRDA to update world regulatory domain
[   51.853104] cfg80211: Exceeded CRDA call max attempts. Not calling CRDA

**Comment by nolegalname** [comment]
Hi!!!!!!

Need to set up  node but not know what is missing what lines what to do??

**Comment by nolegalname** [comment]
Solved problem with USB inside Directory tree

**Comment by nolegalname** [comment]
Now have this problem
$ bitcoind: main.cpp:1836: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.

**Comment by nolegalname** [comment]
Chris helped me to fix it and its working now
